function mrtim

warning off
mrtim_path = fileparts(mfilename('fullpath'));
spm_path = mrtim_path(1:end-length('/toolbox/MRTIM'));
addpath(genpath(spm_path));

fprintf([ ...
'\n' ... 
'================================================== \n' ...
' __   __  ______           _______  ___   __   __ \n' ...
'|  |_|  ||    _ |         |       ||   | |  |_|  | \n' ...
'|       ||   | ||   ____  |_     _||   | |       | \n' ...
'|       ||   |_||_ |____|   |   |  |   | |       | \n' ...
'|       ||    __  |         |   |  |   | |       | \n' ...
'| ||_|| ||   |  | |         |   |  |   | | ||_|| | \n' ...
'|_|   |_||___|  |_|         |___|  |___| |_|   |_| \n' ...
'\n    * MR-BASED HEAD TISSUE MODELLING Toolbox * \n' ...
'================================================== \n \n' ...
]);


gui_path = fileparts(mfilename('fullpath'));
logo_path = [gui_path filesep 'logo/mrtim_logo.png'];
icon_path = [gui_path filesep 'logo/mrtim_icon.png'];

gui = figure('Visible','Off', ...
    'NumberTitle','Off', ...
    'Name','.:: MR-TIM ::.',...
    'Units','Normalized',...
    'Position',[0.025 0.01 0.25 0.86],...
    'Resize','Off',...
    'Menubar','None',...
    'Toolbar','None');

handles = guihandles(gui);
handles.gui = gui;

[logo,~,alpha] = imread(logo_path);
logo = imresize(logo,0.5);
alpha = imresize(alpha,0.5);
ax_logo = axes('Parent',gui,'Position',[0.12 0 0.75 1.75]);
set(ax_logo,'Visible','Off')
l = imshow(logo,'parent',ax_logo);
set(l,'AlphaData',alpha);
uicontrol(gui,'Style','text',...
    'String','MR-based head tissue modelling',...
    'FontName','Tahoma',...
    'FontWeight','bold',...
    'FontSize',18,...
    'ForegroundColor',[85 34 0]/255,...
    'HorizontalAlignment','center',...
    'Position',[15 540 330 30]);
str_mrtim = sprintf([ ...
'MR-TIM performs automated segmentation of whole-head T1-weighted MR images in 12 tissues: ' ...
'brain gray matter (GM), cerebellar GM, brain white matter (WM), cerebellar WM, brainstem, ' ...
'cerebrospinal fluid (CSF), spongy bone, compact bone, muscle, fat, eyes and skin.' ...
]);
uicontrol(gui,'Style','text',...
    'String',str_mrtim,...
    'FontName','Tahoma',...
    'FontSize',14,...
    'ForegroundColor',[85 34 0]/255,...
    'HorizontalAlignment','left',...
    'Position',[15 380 330 150]);
uicontrol(gui,'Style','text',...
    'String','It requires MATLAB 2016b or later versions and it is intended as a toolbox for SPM12.',...
    'FontName','Tahoma',...
    'FontSize',14,...
    'ForegroundColor',[85 34 0]/255,...
    'HorizontalAlignment','left',...
    'Position',[15 370 330 50]);

[icon,~,alpha] = imread(icon_path);
icon = imresize(icon,0.5);
alpha = imresize(alpha,0.5);
ax_icon = axes('Parent',gui,'Unit','pixels','Position',[80 340 200 25]);
set(ax_icon,'Visible','Off')
l = imshow(icon,'parent',ax_icon);
set(l,'AlphaData',alpha);

uicontrol(gui,'Style','text',...
    'String','Download the latest version of the software:',...
    'FontName','Tahoma',...
    'FontSize',14,...
    'ForegroundColor',[85 34 0]/255,...
    'HorizontalAlignment','left',...
    'Position',[15 295 330 30]);
uicontrol(gui,'Style','pushbutton',...
    'String','NITRC',...
    'FontName','Tahoma',...
    'FontWeight','bold',...
    'FontSize',14,...
    'ForegroundColor',[85 34 0]/255,...
    'Position',[70 260 100 40],...
    'Callback',@linknitrc)
uicontrol(gui,'Style','pushbutton',...
    'String','GitHub',...
    'FontName','Tahoma',...
    'FontWeight','bold',...
    'FontSize',14,...
    'ForegroundColor',[85 34 0]/255,...
    'Position',[190 260 100 40],...
    'Callback',@linkgit)
uicontrol(gui,'Style','text',...
    'String','Online user manual: ',...
    'FontName','Tahoma',...
    'FontSize',14,...
    'ForegroundColor',[85 34 0]/255,...
    'HorizontalAlignment','left',...
    'Enable','Inactive',...
    'Position',[15 220 270 30]);
uicontrol(gui,'Style','text',...
    'String','click here.',...
    'FontName','Tahoma',...
    'FontSize',14,...
    'FontAngle','oblique',...
    'ForegroundColor',[85 34 0]/255,...
    'HorizontalAlignment','left',...
    'Enable','Inactive',...
    'ButtonDownFcn',@linkmanual,...
    'Position',[140 220 270 30]);

ax_icon2 = axes('Parent',gui,'Unit','pixels','Position',[80 185 200 25]);
set(ax_icon2,'Visible','Off')
l = imshow(icon,'parent',ax_icon2);
set(l,'AlphaData',alpha);

uicontrol(gui,'Style','text',...
    'String','Developed by G.A. Taberna, D. Mantini',...
    'FontName','Tahoma',...
    'FontSize',14,...
    'ForegroundColor',[85 34 0]/255,...
    'HorizontalAlignment','left',...
    'Position',[15 140 330 30]);
%{
str_cit = sprintf([ ...
'Please cite:\n' ...
'G.A. Taberna, J. Samogin, D. Mantini'
]);
uicontrol(gui,'Style','text',...
    'String',str_cit,...
    'FontName','Tahoma',...
    'FontSize',14,...
    'ForegroundColor',[85 34 0]/255,...
    'HorizontalAlignment','left',...
    'Position',[15 120 330 50]);
%}
set(gui,'Visible','On')

spm_jobman('interactive','','spm.tools.spm_mrtim.run');


function linknitrc(hObject, eventdata, handles)
    web('https://www.nitrc.org/projects/mr-tim', '-browser')

function linkgit(hObject, eventdata, handles)
    web('https://github.com/gtaberna/mrtim', '-browser')
    
function linkmanual(hObject, eventdata, handles)
    web('https://github.com/gtaberna/mrtim/wiki', '-browser')
    